
test_csg_picking: 
	cargo test --test test_csg_picking -- --show-output --include-ignored --test-threads=1 --nocapture

test_mesh_draw: 
	cargo test --test test_mesh_draw -- --show-output --include-ignored --test-threads=1 --nocapture
test_points_draw: 
	cargo test --test test_points_draw -- --show-output --include-ignored --test-threads=1 --nocapture